<ul class="nav navbar-nav">
    <?php
    /**
     * @var Zend\Navigation\Page\Mvc $page
     */
    foreach ($this->container as $page) : ?>

        <?php if ($page->isActive()) : ?>
            <li class="active">
        <?php else : ?>
            <li>
        <?php endif; ?>
        <a href="<?= $this->url(
            $page->getRoute(),
            [
                'localization' => 'en',
            ]
        ) ?>">
            <?= $this->translate($page->getLabel()) ?>
        </a>
        </li>
    <?php endforeach; ?>
</ul>
