<?php
/**
 * @var LoginForm $form
 */

use User\Form\LoginForm;

$form->setAttributes(
    [
        'action' => $this->url('login', []),
        'id' => 'loginForm',
    ]
);

$username = $form->get(LoginForm::USERNAME);
$username->setAttributes(
    [
        'class' => 'form-control',
        'placeholder' => 'Username',
    ]
);

$password = $form->get(LoginForm::PASSWORD);
$password->setAttributes(
    [
        'class' => 'form-control',
        'placeholder' => 'Password',
    ]
);

$rememberMe = $form->get(LoginForm::REMEMBER_ME);

$submit = $form->get(LoginForm::SUBMIT);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

    <fieldset>
        <div class="form-group">
            <?= $this->formRow($username) ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($password) ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($rememberMe, 'append') ?>
        </div>
    </fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();
