<?php

namespace Blog\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
    /**
     * @return int
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getCount()
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $queryCount = $queryBuilder->select('COUNT(Language.id)')
            ->from(Language::class, 'Language');
        return (int)$queryCount->getQuery()->getSingleScalarResult();
    }

    /**
     * @return mixed
     */
    public function getCodes()
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        $query = $queryBuilder->select('Language.languageCode')
            ->from(Language::class, 'Language');
        return $query->getQuery()->getResult();
    }

    /**
     * @param string $code
     *
     * @return null|object
     */
    public function getByCode($code)
    {
        return $this->findOneBy(['languageCode' => $code]);
    }
}
