<?php
/**
 * @var \Blog\Entity\Post[] $posts
 * @var string              $localization
 * @var bool                $isUserLogged
 */
?>

<div class="list-group">
    <?php
    /**
     * @var \Blog\Entity\Post $post
     */
    foreach ($posts as $post) :
        /** @var \Blog\Entity\PostLanguage $postLanguage */
        $postLanguage = $post->getPostLanguage($localization);
        ?>
        <div class="list-group-item">
            <h4 class="list-group-item-heading">
                <a href="<?= $this->url('blog/detail', ['id' => $post->getId(), 'localization' => $localization]) ?>">
                    <?= $postLanguage->getTitle() ?>
                </a>
            </h4>
            <?php if ($isUserLogged) : ?>
                <div class="btn-group" role="group" aria-label="Post actions">
                    <a class="btn btn-xs btn-default"
                       href="<?= $this->url('blog/edit', ['id' => $post->getId(), 'localization' => $localization]) ?>">
                        <?= $this->translate('Edit') ?>
                    </a>
                    <button class="btn btn-xs btn-danger delete-post-button"
                            data-post-id="<?= $post->getId() ?>"
                            data-delete-url="<?= $this->url('blog/deletePost') ?>"
                            data-confirm-text="<?= $this->translate('Are you sure you want to delete this post?') ?>">
                        <?= $this->translate('Delete') ?>
                    </button>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach ?>
</div>
